[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 确保 ISR 功能正常工作
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# 配置函数超时时间
[functions]
  included_files = [".next/**"]

# 配置重定向规则（如果需要）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

  # 声明路由映射
[[edge_functions]]
  function = "auth"           # 函数文件名
  path = "/*"            # 匹配路径


[[edge_functions]]
  function = "transform"           # 函数文件名
  path = "/*"            # 匹配路径
